services:
  music_analysis:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"  # For Jupyter Notebook
    platform: linux/amd64  # Specify platform for x86_architecture
    environment:
      - TENSORFLOW_CPU_ONLY=1
      - PYTHONUNBUFFERED=1